export const ChannelExecCommands = [
  "AddQueueMember", "AgentLogin", "AgentRequest",
  "AGI", "AlarmReceiver", "AMD", "AttendedTransfer",
  "AudioSocket", "Authenticate", "Background",
  "BackGround", "BackgroundDetect", "BlindTransfer",
  "Bridge", "BridgeAdd", "BridgeWait", "Busy",
  "CallCompletionCancel", "CallCompletionRequest",
  "CELGenUserEvent", "ChangeMonitor", "ChanIsAvail",
  "ChannelRedirect", "ChanSpy", "ClearHash",
  "ConfBridge", "ConfKick", "Congestion",
  "ContinueWhile", "ControlPlayback", "DAHDIScan",
  "DateTime", "DBdeltree", "DeadAGI", "Dial",
  "Dictate", "Directory", "DISA", "DumpChan",
  "EAGI", "Echo", "Else", "ElseIf", "EndIf",
  "EndWhile", "ExecIf", "ExecIfTime", "ExitIf",
  "ExitWhile", "ExtenSpy", "ExternalIVR", "Festival",
  "FollowMe", "ForkCDR", "Gosub", "GosubIf", "Goto",
  "GotoIf", "GotoIfTime", "HangupCauseClear", "If",
  "ImportVar", "Incomplete", "Log", "Macro",
  "MacroExclusive", "MacroExit", "MacroIf",
  "MessageSend", "Milliwatt", "MinivmAccMess",
  "MinivmDelete", "MinivmGreet", "MinivmMWI",
  "MinivmNotify", "MinivmRecord", "MixMonitor",
  "Monitor", "Morsecode", "MP3Player", "MSet",
  "MusicOnHold", "NoCDR", "ODBC_Commit",
  "ODBC_Rollback", "ODBCFinish", "Originate",
  "Page", "Park", "ParkAndAnnounce", "ParkedCall",
  "PauseMonitor", "PauseQueueMember", "Pickup",
  "PickupChan", "PlayTones", "PrivacyManager",
  "Proceeding", "Progress", "Queue", "QueueLog",
  "QueueUpdate", "RaiseException", "Read",
  "ReadExten", "ReceiveFAX", "ReceiveMF", "ReceiveSF",
  "ReceiveText", "Record", "Reload", "RemoveQueueMember",
  "ResetCDR", "RetryDial", "Return", "Ringing", "SayAlpha",
  "SayAlphaCase", "SayDigits", "SayMoney", "SayNumber",
  "SayOrdinal", "SayPhonetic", "SayUnixTime", "SendDTMF",
  "SendFAX", "SendMF", "SendSF", "SendText", "Set",
  "SetAMAFlags", "SMS", "SoftHangup", "SpeechActivateGrammar",
  "SpeechBackground", "SpeechCreate", "SpeechDeactivateGrammar",
  "SpeechDestroy", "SpeechLoadGrammar", "SpeechProcessingSound",
  "SpeechStart", "SpeechUnloadGrammar", "StackPop",
  "StartMusicOnHold", "Stasis", "StopMixMonitor", "StopMonitor",
  "StopMusicOnHold", "StopPlayTones", "StoreDTMF", "StreamEcho",
  "System", "TestClient", "TestServer", "ToneScan", "Transfer",
  "TryExec", "TrySystem", "UnpauseMonitor", "UnpauseQueueMember",
  "UserEvent", "VMAuthenticate", "VMSayName", "VoiceMail",
  "VoiceMailMain", "VoiceMailPlayMsg", "Wait", "WaitDigit",
  "WaitExten", "WaitForCondition", "WaitForNoise", "WaitForRing",
  "WaitForSilence", "WaitForTone", "WaitUntil", "While", "Zapateller"
] as const;
